apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: smoggy-tahr-go 
  janus-idp.io/tekton: smoggy-tahr-go
  backstage.io/kubernetes-id: smoggy-tahr-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: smoggy-tahr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  