apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: smoggy-tahr-go-gitops
  description: This is GitOps manifest for smoggy-tahr-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: smoggy-tahr-go
    janus-idp.io/tekton: smoggy-tahr-go 
    backstage.io/kubernetes-id: smoggy-tahr-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:smoggy-tahr-go
